### ISSUE TITLE
Changes I had to make to get it to work

### ISSUE THREAD

**Issue by loglow** [archont94/mutable-env#1]
Thanks for making this, since trying to use the Vagrant/VirtualBox mutable-dev-environment with an arm64 (M2) mac wasn't working for me. The VM would just abort on boot, probably because the arm64 version of VirtualBox is still in beta, but who knows. I wasn't able to resolve the issue myself, so I tried this. I have almost no previous experience with Docker.

Anyway, I had to make some small changes to get things to work.

Attempting to run the mutable-env command would give me an error:

```
Unable to find image 'mutable-env:latest' locally
docker: Error response from daemon: pull access denied for mutable-env, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
"docker "${docker_args[@]}"" command filed with exit code 125.
```

So, I had to change line 22 in /usr/local/bin/mutable-env from:

`docker_args+=(mutable-env:latest)`

to:

`docker_args+=(archont94/mutable-env:latest)`

This resolved the problem.

Also, I'm just using the environment to compile binaries and not flash them with a USB device.

So, I had to comment out line 20 in /usr/local/bin/mutable-env:

`#docker_args+=( $(find_device "ST-LINK") )`

At this point the commands would work and the compilation of binaries was successful.

**Comment by archont94** [comment]
@loglow thanks for feedback, I made some changes to address your problems: https://github.com/archont94/mutable-env/commit/26d87e6861647fe43a6b61acee30d8b72eb96a97
